spring.application.name=Rjugo
# MySQL ?? ??
spring.datasource.url=jdbc:mysql://localhost:3306/data?useSSL=false&serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA ?? (??)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
